{% set name = "pyironflow" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyironflow-{{ version }}.tar.gz
  sha256: 2a880f1747c8c311ae65df4cfdb67a4ed8dd7ee9201b1b0f2c8c4e6e8e8c08a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python 3.11
    - hatchling
    - hatch-jupyter-builder
    - versioneer
    - pip
    - anywidget
    - esbuild
    - ipytree
    - ipython
    - ipywidgets
    - nodejs
    - traitlets
    - pyiron_workflow
  run:
    - python >=3.11,<3.13
    - anywidget
    - traitlets
    - ipytree
    - ipython >=8.11,<9
    - ipywidgets
    - pyiron_workflow >=0.12.1,<1

test:
  imports:
    - pyironflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyironFlow
  summary: react xyflow for pyiron
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmrv
    - jan-janssen
