{% set name = "pyironflow" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyironflow-{{ version }}.tar.gz
  sha256: 46133a7fdfeeb70121dc6ece49d52b09ddce12ab84b15bd4e4f214d7ad14c653

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - hatchling
    - hatch-jupyter-builder
    - versioneer
    - pip
    - anywidget
    - esbuild
    - ipython
    - ipywidgets
    - nodejs
    - traitlets
    - pyiron_workflow
  run:
    - python >=3.9,<3.13
    - anywidget
    - traitlets
    - ipython
    - ipywidgets
    - pyiron_workflow

test:
  imports:
    - pyironflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyironFlow
  summary: react xyflow for pyiron
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
