{% set name = "pyironflow" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyironflow-{{ version }}.tar.gz
  sha256: f0cd729dd9791173cc650bdf0d991350fc68cd9100959ce3316abaca9b4d51df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder
    - versioneer
    - pip
    - anywidget
    - esbuild
    - ipytree
    - ipython
    - ipywidgets
    - nodejs
    - traitlets
    - pyiron_workflow
  run:
    - python >={{ python_min }},<3.13
    - anywidget
    - traitlets
    - ipytree
    - ipython
    - ipywidgets
    - pyiron_workflow

test:
  imports:
    - pyironflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyironFlow
  summary: react xyflow for pyiron
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmrv
    - jan-janssen
