schema_version: 1

context:
  name: pyironflow
  version: "0.0.21"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyironflow-${{ version }}.tar.gz
  sha256: 5c177fdd2b9b397dd39ab6886c56b91fcb7d3831b8d73ac418acab12b61ca813

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.11.*
    - hatchling
    - hatch-jupyter-builder
    - versioneer
    - pip
    - anywidget
    - esbuild
    - ipytree
    - ipython
    - ipywidgets
    - nodejs
    - traitlets
    - pyiron_workflow
  run:
    - python >=${{ python_min }},<3.13
    - anywidget
    - traitlets
    - ipytree
    - ipython >=8.11,<9
    - ipywidgets
    - pyiron_workflow >=0.12.1,<1

tests:
  - python:
      imports:
        - pyironflow
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: react xyflow for pyiron
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/pyironFlow

extra:
  recipe-maintainers:
    - pmrv
    - jan-janssen
    - srmnitc
